#+title: Project Reading
#+AUTHOR: Pranav Kalsi
#+BIBLIOGRAPHY: Papers/biblio.bib
Last modified: [2025-05-10 Sat]
This file contains the important and relevant things from the reading resources for the project. It also contains doubts which are unresolved.

Project progress is maintained here [[file:Progress.org][Progress]].
Communication with professor and personal goals is maintained here [[file:Project_update.org][Project_Updates]].
* Converging point method
The method is beautifully explained in this website: https://physics.weber.edu/palen/clearinghouse/labs/hyades/disthyad.html.
* Reading Paper:
** [[file:Papers/Joshi_2020_MNRAS_492_3602.pdf][Photometric, kinematic, and variability study in the young open cluster NGC 1960]] [cite:@joshi20_photom_kinem_variab_study_young] 
*** Membership determination (Section 4):
This section of the paper focuses on the determining the membership probability of a star in the image field, by assuming a few confirmed cluster members.
In general an image will have stars from clusters and foreground as well as background.
Using Gaia DR2, data proper-motion is plotted as Vector Point Diagram (VPD). And the cluster members are assigned by chosing stars which form a dense cluster of points in VPD.
     #+BEGIN_QUOTE 
    [fn:1] The centre of the circular region confining the
 probable cluster members was determined by maximum density
 method in the proper motion plane which is found to lie at (μx , μy )
 ≡ (μα cosθ, μδ ) ≈ (−0.13, −3.37) mas yr−1 .
 The radius of the circle
 was derived by plotting the stellar density as a function of radial
 distance in the proper motion plane as illustrated in Fig. 2. We fit the stellar density profile with a function similar to the one used to characterize the radial profiles of star clusters in the galaxies.
     #+END_QUOTE
     *Membership probability*  
#+begin_quote
\[
P_\mu(i) = \frac{n_c \cdot \phi^v_c(i)}{n_c \cdot \phi^v_c(i) + n_f \cdot \phi^v_f(i)}
\]
\[
\phi^v_c(i) = \frac{1}{2\pi \sqrt{(\sigma_{xc}^2 + \epsilon_{xi}^2)(\sigma_{yc}^2 + \epsilon_{yi}^2)}} \exp\left\{ - \frac{1}{2} \left[ \frac{(\mu_{xi} - \mu_{xc})^2}{\sigma_{xc}^2 + \epsilon_{xi}^2} + \frac{(\mu_{yi} - \mu_{yc})^2}{\sigma_{yc}^2 + \epsilon_{yi}^2} \right] \right\}
\]

\[
\phi^v_f(i) = \frac{1}{2\pi \sqrt{1 - \gamma^2} \sqrt{(\sigma_{xf}^2 + \epsilon_{xi}^2)(\sigma_{yf}^2 + \epsilon_{yi}^2)}}
\
\exp\left\{ - \frac{1}{2(1 - \gamma^2)} \left[ \frac{(\mu_{xi} - \mu_{xf})^2}{\sigma_{xf}^2 + \epsilon_{xi}^2} - \frac{2\gamma (\mu_{xi} - \mu_{xf})(\mu_{yi} - \mu_{yf})}{\sqrt{(\sigma_{xf}^2 + \epsilon_{xi}^2)(\sigma_{yf}^2 + \epsilon_{yi}^2)}} - \frac{(\mu_{yi} - \mu_{yf})^2}{\sigma_{yf}^2 + \epsilon_{yi}^2} \right] \right\}
\]


\[
\gamma = \frac{(\mu_{xi} - \mu_{xf})(\mu_{yi} - \mu_{yf})}{\sigma_{xf} \sigma_{yf}}
\]

#+end_quote
*Parallax criteria on membership selection*
By measuring the parallax of the stars, we further constrain the cluster members by eliminating all those stars whose parallax is 3\sigma away from the mean cluster parallax, which is a gaussian. 
* Footnotes
[fn:1] Reffering to figure 1 in [cite:@joshi20_photom_kinem_variab_study_young]. 
