#!/bin/bash

# Step 1: Take inputs
read -p "Enter the number of frequency channels needed: " n_chan
read -p "Enter the list of required number of subints (space-separated): " subints_list
read -p "Enter the path of the PSRFITS file: " psrfits_file

# Step 2: Prepare required files
pam --setnchn $n_chan -e "{$n_chan}tt" $psrfits_file

for subint in $subints_list; do
    # Construct output file name
    output_file="${num_channels}chan_${subint}subints"

    # Crunch frequency channels
    #pam -c $num_channels $psrfits_file -o temp.fits

    # Crunch subintegrations
    #psrshrink -n $subint temp.fits -o $output_file
    pam --setnsub $subint $psrfits_file -e tt
    mv $psrfits_file.tt $output_file
    # Remove temporary file
    #rm temp.fits
done


